// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:doctor_reservation_app/features/home/data/model/specialization_response_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(DoctorsAdapter());
    registerAdapter(SpecializationResponseModelAdapter());
    registerAdapter(SpecializationsDataAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(DoctorsAdapter());
    registerAdapter(SpecializationResponseModelAdapter());
    registerAdapter(SpecializationsDataAdapter());
  }
}
